export const SIGNIN = 'SIGNIN'
export const SIGNOUT = 'SIGNOUT'
export const SIGNUP = 'SIGNUP'
export const PROFILE = 'PROFILE'

export const USERS_GET = 'USERS_GET'
export const REGULARS_GET = 'REGULARS_GET'
export const USER_GET = 'USER_GET'
export const USER_CREATE = 'USER_CREATE'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_DELETE = 'USER_DELETE'

export const MEALS_GET = 'MEALS_GET'
export const MEAL_GET = 'MEAL_GET'
export const MEAL_CREATE = 'MEAL_CREATE'
export const MEAL_UPDATE = 'MEAL_UPDATE'
export const MEAL_DELETE = 'MEAL_DELETE'
export const CALORIES_TODAY = 'CALORIES_TODAY'